lsi_market:
    resource: "@LSIMarketBundle/Resources/config/routing.yml"
    prefix:   /market

# Les routes de FOSUserBundle
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"





